export const FieldRole: any;
export const OccurrenceMaterializationMode: any;
export const OccurrenceNextTrigger: any;
export const PriorityConfig: any;
export const Reminder: any;
export const SpecFieldMapping: any;
export const StatusConfig: any;
export const TASKNOTES_SPEC_VERSION: any;
export const TaskCreationData: any;
export const TaskDependency: any;
export const TaskInfo: any;
export const TaskNotesModelConfig: any;
export const TaskValidationIssue: any;
export const TaskValidationResult: any;
export const TimeEntry: any;
export const UserMappedField: any;
export const evaluateCoreValidation: any;
export const resolveModelConfig: any;
export const validateTask: any;

export type FieldRole = any;
export type PriorityConfig = any;
export type Reminder = any;
export type SpecFieldMapping = any;
export type StatusConfig = any;
export type TaskCreationData = any;
export type TaskDependency = any;
export type TaskNotesModelConfig = any;
export type TaskValidationIssue = any;
export type TaskValidationResult = any;
export type TimeEntry = any;
export type UserMappedField = any;
